name: Daily Commit

on:
  schedule:
    - cron: '0 7 * * *' # Every day at midnight UTC
  workflow_dispatch: # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make a change (update timestamp)
        run: |
          echo "Last updated: $(date -u)" > last-updated.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last-updated.txt
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit"
          git push
